<a href="https://colab.research.google.com/github/Iveynganga/PYTHON-DATA-ANALYSIS/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
import numpy as np

np.__version__

'1.25.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
import numpy as np

a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [26]:
arr = np.zeros((10, 10))
memory_size_bytes = arr.nbytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
import numpy as np
np.add

<ufunc 'add'>

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
import numpy as np

b = np.zeros(10)
b[4] = 1


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [16]:
import numpy as np

c = np.arange(10, 50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
import numpy as np

#sample vector
vector = np.array([1, 2, 3, 4, 5])
reversed_vector = vector[::-1]
print(reversed_vector)

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
values = np.arange(9)
matrix = values.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [30]:
import numpy as np

list  = [1,2,0,0,4,0]
arr = np.array(list)
x = np.nonzero(arr)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
identity_matrix = np.eye(3)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
y = np.random.rand(3, 3, 3)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [32]:
random_array = np.random.rand(10, 10)
minimum_value = random_array.min()
maximum_value = random_array.max()


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
random_vector = np.random.rand(30)
mean_value = random_vector.mean()


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [33]:
x = np.ones((5, 5))

x[1:-1, 1:-1] = 0



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
